Make sure `m_state` with internal linkage is defined
Fixes the following error when building: error C7631: 'm_state': variable with internal linkage declared but not defined